import { EntityBuilder } from "../generator/EntityBuilder.js";

export class NPCGeneratorApp {

    static async _callLLM(prompt, apiKey) {
        if (!apiKey) {
            throw new Error("No API Key provided. Please set your LLM API Key in Module Settings.");
        }

        const systemInstruction = `You are a Pathfinder 2e assistant analyzing a request for an NPC generated by the user.
You must return only a valid JSON object with EXACTLY these keys:
- "name": string (a fitting, culturally appropriate name for the NPC)
- "biography": string (a short 1-2 sentence background or roleplaying motivation)
- "level": integer (-1 to 24)
- "role": string (must be exactly one of: "brute", "skirmisher", "spellcaster", "sniper", "soldier")
- "spellTradition": string (if role is spellcaster, one of: "arcane", "divine", "occult", "primal". Otherwise null)
- "spellcastingType": string (if role is spellcaster, one of: "prepared", "spontaneous", "innate". Otherwise null)
- "generateEquipment": boolean (true if the prompt implies they need gear/weapons, false otherwise)
- "equipment": array of strings (Specific PF2e item names the NPC should have, e.g. ["Rapier", "Leather Armor", "Healing Potion", "Bag of Holding", "Scroll of Heal"]. Include magical items, potions, gold, and other gear that makes sense from their background information. Empty array if none)
- "spells": array of strings (Specific PF2e spell names the NPC should have, e.g. ["Fireball", "Shield"]. Empty array if none)
- "features": array of strings (Specific PF2e monster ability names, e.g. ["Sneak Attack", "Nimble Dodge"]. Empty array if none)
- "skills": array of objects (Specific PF2e skill modifiers, format: [{"id": "ste", "mod": 14}, {"id": "acr", "mod": 12}]. Empty array if none)
Do not provide markdown formatting, just the raw JSON object. Evaluate the prompt and pick the best matching role and level.`;

        try {
            const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    system_instruction: {
                        parts: [{ text: systemInstruction }]
                    },
                    contents: [{
                        parts: [{ text: `User request: "${prompt}"` }]
                    }],
                    generationConfig: {
                        temperature: 0.1,
                        response_mime_type: "application/json"
                    }
                })
            });

            if (!response.ok) {
                const errText = await response.text();
                throw new Error(`API error ${response.status}: ${errText}`);
            }

            const data = await response.json();
            const textResponse = data.candidates?.[0]?.content?.parts?.[0]?.text;

            if (!textResponse) throw new Error("Invalid response format from LLM.");

            return JSON.parse(textResponse.trim());
        } catch (error) {
            console.error("PF2e NPC Generator | LLM API Error:", error);
            throw error;
        }
    }

    static async render() {
        // Prepare context data
        const roles = {
            "brute": "Brute (High HP, High Damage, Low AC/Saves)",
            "skirmisher": "Skirmisher (High Mobility, Good AC/Attack)",
            "spellcaster": "Spellcaster (Low HP/AC, High Spells/DCs)",
            "sniper": "Sniper (High Ranged Attack, Low HP)",
            "soldier": "Soldier (High AC, Moderate HP/Attack)"
        };

        const templateData = {
            level: 1,
            roles: roles,
            role: "brute",
            generateEquipment: true
        };

        // Render the template manually
        const content = await renderTemplate("modules/pf2e-npc-gen/templates/generator-app.hbs", templateData);

        // Create a classic Dialog
        new Dialog({
            title: "Pathfinder 2e NPC Generator",
            content: content,
            buttons: {
                manual: {
                    icon: '<i class="fas fa-hammer"></i>',
                    label: "Generate Manually",
                    callback: async (html) => {
                        const form = html.find('form')[0] || html[0];

                        const eliteCheckbox = form.querySelector("#template-elite")?.checked;
                        const weakCheckbox = form.querySelector("#template-weak")?.checked;
                        let templateAdjustment = null;
                        if (eliteCheckbox) templateAdjustment = "elite";
                        if (weakCheckbox) templateAdjustment = "weak";

                        const levelInput = form.querySelector("#npc-level");
                        const roleInput = form.querySelector("#npc-role");
                        const equipCheckbox = form.querySelector("#generate-equipment");

                        const level = parseInt(levelInput?.value || "1", 10);
                        const role = roleInput?.value || "brute";
                        const genEquipment = equipCheckbox?.checked ?? true;
                        const name = null;
                        const biography = null;
                        const spellTradition = null;
                        const spellcastingType = null;

                        ui.notifications.info(`Generating Level ${level} ${role} NPC...`);
                        await NPCGeneratorApp._executeGeneration({
                            level, roleKey: role, generateEquipment: genEquipment,
                            name, biography, templateAdjustment, spellTradition, spellcastingType
                        });
                    }
                },
                ai: {
                    icon: '<i class="fas fa-robot"></i>',
                    label: "Generate via AI",
                    callback: async (html) => {
                        const form = html.find('form')[0] || html[0];

                        const promptInput = form.querySelector("#ai-prompt")?.value?.trim();
                        if (!promptInput) {
                            ui.notifications.warn("Please enter an AI prompt first.");
                            return;
                        }

                        const eliteCheckbox = form.querySelector("#template-elite")?.checked;
                        const weakCheckbox = form.querySelector("#template-weak")?.checked;
                        let templateAdjustment = null;
                        if (eliteCheckbox) templateAdjustment = "elite";
                        if (weakCheckbox) templateAdjustment = "weak";

                        ui.notifications.info("Interpreting Prompt with AI... Please wait.");
                        const apiKey = game.settings.get("pf2e-npc-gen", "llmApiKey");

                        try {
                            const aiData = await NPCGeneratorApp._callLLM(promptInput, apiKey);
                            ui.notifications.info(`AI decided: ${aiData.name} - Level ${aiData.level} ${aiData.role} (Equipment: ${aiData.generateEquipment})`);

                            await NPCGeneratorApp._executeGeneration({
                                level: aiData.level,
                                roleKey: aiData.role,
                                generateEquipment: aiData.generateEquipment,
                                name: aiData.name,
                                biography: aiData.biography,
                                spellTradition: aiData.spellTradition,
                                spellcastingType: aiData.spellcastingType,
                                templateAdjustment,
                                equipmentList: aiData.equipment,
                                spellList: aiData.spells,
                                featureList: aiData.features,
                                skillList: aiData.skills
                            });
                        } catch (e) {
                            ui.notifications.error(e.message || "Failed to parse prompt via AI.");
                        }
                    }
                },
                cancel: {
                    icon: '<i class="fas fa-times"></i>',
                    label: "Cancel"
                }
            },
            default: "manual",
            render: html => console.log("PF2e NPC Generator | Dialog rendered"),
            close: html => console.log("PF2e NPC Generator | Dialog closed")
        }, {
            width: 450,
            classes: ["dialog", "pf2e-npc-gen-app"]
        }).render(true);
    }

    static async _executeGeneration(params) {
        try {
            const builder = new EntityBuilder(params);
            const newActor = await builder.generateNPC();

            if (newActor) {
                ui.notifications.info(`Successfully created NPC: ${newActor.name}`);
                newActor.sheet.render(true);
            } else {
                ui.notifications.warn("NPC creation finished, but the actor object was not returned correctly.");
            }
        } catch (error) {
            console.error("PF2e NPC Generator | Error building NPC:", error);
            ui.notifications.error("Failed to generate NPC. See console for details.");
        }
    }
}
